### ISSUE TITLE
What should be changed from the home assistant side

### ISSUE THREAD

**Issue by harisraharjo** [tmikoss/use-homeassistant#1]
Hey first of all thank you for making this great library! 
Is there anything that should be changed from the home assistant side? If I remember correctly, we need to add "api" property in the configuration.yaml

**Comment by tmikoss** [comment]
@harisraharjo I don't believe I ran into any blocking issues. However, I have since stopped development, and migrated my use cases to https://github.com/shannonhochkins/ha-component-kit - perhaps you can request feedback there.
